#!/bin/sh

# edit files in a new Mac OS X iTerm window v1.0
# originally developed for use with the It's All Text Firefox extension,
#   https://addons.mozilla.org/en-US/firefox/addon/4125
# Copyright (c) 2010, John Morrissey <jwm@horde.net>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#	* Redistributions of source code must retain the above copyright notice,
#	  this list of conditions and the following disclaimer.
#	* Redistributions in binary form must reproduce the above copyright
#	  notice, this list of conditions and the following disclaimer in the
#	  documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

osascript \
	-e 'to replaceText(find, replace, subject)' \
		-e 'set prevTIDs to text item delimiters of AppleScript' \
		-e 'set text item delimiters of AppleScript to find' \
		-e 'set subject to text items of subject' \
		\
		-e 'set text item delimiters of AppleScript to replace' \
		-e 'set subject to "" & subject' \
		-e 'set text item delimiters of AppleScript to prevTIDs' \
		\
		-e 'return subject' \
	-e 'end replaceText' \
	\
	-e 'on run argv' \
		-e "set escaped_filename to replaceText(\"'\", \"'\\\\''\", item 1 of argv)" \
		\
		-e 'tell application "iTerm"' \
			-e 'activate' \
			-e 'make new terminal' \
			 \
			-e 'tell the last terminal' \
				-e 'make new session at the end of sessions' \
				 \
				-e 'tell the last session' \
					-e 'set name to item 1 of argv' \
					-e 'exec command "/bin/bash"' \
					-e 'write text "\"${VISUAL:-${EDITOR:-vi}}\" '\''" & escaped_filename & "'\''; exit"' \
				-e 'end tell' \
			-e 'end tell' \
		-e 'end tell' \
	-e 'end run' \
	"$1"
