#!/bin/sh

# extract scrollback from minicom core file
# Copyright (c) 2009, John Morrissey <jwm@horde.net>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


BINARY=~/minicom
CORE=~/minicom.core.18829

if [ -e src/main.c ]; then
	cd src
elif [ ! -e main.c ]; then
	echo "$(basename "$0"): must be run in the minicom src directory."
	exit 1
fi

get_from_gdb()
{
	if [ -z "$1" ] || [ -z "$2" ]; then
		return 1
	fi

	gdb -q "$1" "$2" 2>/dev/null | \
		sed -n \
		    -e '/^Using /,/^#0 /d' \
		    -e 's/(gdb) //g' \
		    -e 's/^\$[0-9]\{1,\} = \([0-9]\{1,\}\)$/\1/p' \
		    -e "s/^\\\$[0-9]\\{1,\\} = [0-9]\\{1,\\} '\(.\)'$/\1/p"
}

lines=$(
	(echo -e 'print us->histlines\nquit'; sleep 0.5) | \
	get_from_gdb $BINARY $CORE
)
cols=$(
	(echo -e 'print us->xs\nquit'; sleep 0.5) | \
	get_from_gdb $BINARY $CORE
)

(
	echo 'set pagination off'

	i=0
	bytes=$(($lines * $cols))
	while [ $i -lt $bytes ]; do
		echo "p/c (us->histbuf + $i)->value"
		i=$(($i + 1))
	done

	echo 'quit'
	sleep 5
) | get_from_gdb $BINARY $CORE | \
	tr -d '\n' | \
	fold -w $cols | \
	sed 's/[[:space:]]\{1,\}$//'
