#!/bin/bash

# US Treasury Security price scraper
# Copyright (c) 2007, John Morrissey <jwm@horde.net>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of Version 2 of the GNU General Public License as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

price=$(wget --quiet --output-document=- 'http://reports.finance.yahoo.com/z2?ce=4915552143561495816953&q=b%3d1%26cpl%3d2.000000%26cpu%3d2.000000%26mtl%3d-1%26mtu%3d-1%26pr%3d0%26rl%3d-1%26ru%3d-1%26sf%3dm%26so%3da%26stt%3d-%26tt%3d1%26yl%3d-1.000000%26ytl%3d-1.000000%26ytu%3d-1.000000%26yu%3d-1.000000' | \
	sed -n '/Price/s/.*\([[:digit:]][[:digit:]]\{1,\}\.[[:digit:]]\{2\}\).*/\1/p')
if [ -z "$price" ]; then
	echo "Couldn't obtain price."
	exit 1
fi

echo $price >/var/cache/cricket/tips-jul2014
